export const appConfig = {
  name: "La Trobe Content Distribution Hub",
  assessment: "Cloud Based Applications — Assessment 1",
  version: "1.0.0",
  git: {
    commitCount: 33,
    branch: "main",
    commits: [
      { hash: "83717ab", date: "26 Jul 2026", branch: "main", message: "Initial commit from Create Next App" },
      { hash: "e1e51ad", date: "26 Jul 2026", branch: "feature/project-foundation", message: "chore(project): initialise Next.js application" },
      { hash: "e7875f4", date: "26 Jul 2026", branch: "main", message: "merge: project foundation" },
      { hash: "0037df1", date: "26 Jul 2026", branch: "main", message: "merge: design system and layout" },
      { hash: "33863b7", date: "26 Jul 2026", branch: "feature/design-system-layout", message: "feat(layout): add shared application shell and design system" },
      { hash: "5e5d724", date: "26 Jul 2026", branch: "main", message: "merge: responsive navigation" },
      { hash: "a79850d", date: "26 Jul 2026", branch: "feature/responsive-navigation", message: "feat(navigation): add responsive sidebar hamburger menu and breadcrumbs" },
      { hash: "13ac2a5", date: "26 Jul 2026", branch: "main", message: "merge: theme system" },
      { hash: "9e60805", date: "26 Jul 2026", branch: "feature/theme-system", message: "feat(theme): implement persistent light and dark themes" },
      { hash: "e23648a", date: "26 Jul 2026", branch: "main", message: "merge: user selection" },
      { hash: "adc01ed", date: "26 Jul 2026", branch: "feature/user-selection", message: "feat(user): add mock user selection workflow" },
      { hash: "3c38f02", date: "26 Jul 2026", branch: "main", message: "merge: dashboard" },
      { hash: "bc9c863", date: "26 Jul 2026", branch: "feature/dashboard", message: "feat(dashboard): build content distribution dashboard" },
      { hash: "869dfb5", date: "26 Jul 2026", branch: "main", message: "merge: posts module" },
      { hash: "eaefa9b", date: "26 Jul 2026", branch: "feature/posts-module", message: "feat(posts): add internal and external posts views" },
      { hash: "d644479", date: "26 Jul 2026", branch: "main", message: "merge: publishing workflow" },
      { hash: "63ce13b", date: "26 Jul 2026", branch: "feature/publishing-workflow", message: "feat(publishing): add reusable mock publishing workflow" },
      { hash: "371e503", date: "26 Jul 2026", branch: "main", message: "merge: channel management" },
      { hash: "7bcb509", date: "26 Jul 2026", branch: "feature/channels", message: "feat(channels): add subject channel management" },
      { hash: "478ea70", date: "26 Jul 2026", branch: "main", message: "merge: settings" },
      { hash: "9ea091f", date: "26 Jul 2026", branch: "feature/settings", message: "feat(settings): add appearance and RSS subscription preferences" },
      { hash: "045ee5c", date: "26 Jul 2026", branch: "feature/workflow", message: "feat(workflow): visualise RSS content distribution process" },
      { hash: "f2cdadc", date: "26 Jul 2026", branch: "main", message: "merge: workflow visualisation" },
      { hash: "0e7e890", date: "26 Jul 2026", branch: "main", message: "merge: about and video" },
      { hash: "39830ad", date: "26 Jul 2026", branch: "feature/about", message: "feat(about): add assessment details and demonstration video" },
      { hash: "c2aa142", date: "26 Jul 2026", branch: "feature/accessibility-polish", message: "fix(accessibility): improve keyboard contrast and responsive behaviour" },
      { hash: "e89b258", date: "26 Jul 2026", branch: "main", message: "merge: accessibility and responsive polish" },
      { hash: "01ccccc", date: "26 Jul 2026", branch: "main", message: "merge: final documentation and release" },
      { hash: "880786f", date: "26 Jul 2026", branch: "docs/final-documentation", message: "docs(project): complete assessment documentation" },
      { hash: "86b969e", date: "26 Jul 2026", branch: "main", message: "merge: settings reset and hydration fixes" },
      { hash: "6dc38d5", date: "26 Jul 2026", branch: "fix/settings-reset-and-theme-script", message: "fix(settings): add workspace reset and align subscription toggles" },
      { hash: "cf8960e", date: "27 Jul 2026", branch: "main", message: "feat(settings): show project git commit history" },
      { hash: "HEAD", date: "27 Jul 2026", branch: "main", message: "feat(settings): add expandable chronological Git history" },
    ],
  },
  student: {
    name: "REPLACE WITH REAL NAME",
    number: "REPLACE WITH REAL STUDENT NUMBER",
  },
} as const;
